### ISSUE TITLE
MVPリリース レビュー依頼

### ISSUE THREAD

**Issue by shimada-ryuga-56a** [shimada-ryuga-56a/people1_history#214]
## 各種情報
**【サービス概要】**
PEOPLE 1というアーティストの、ライブ・楽曲の概要やエピソード、豆知識などが集約されているWebアプリです。
イメージとしては、WikipediaのPEOPLE 1の情報だけに特化したバージョンです。
ユーザーは、ライブ終了後など、いつでも自由に情報の書き込み・閲覧が可能です。

**【MVPで検証する事柄】**
* Xでのユーザー認証
* [楽曲一覧画面](https://people1-history.fly.dev/songs)の表示
* [楽曲詳細画面](https://people1-history.fly.dev/songs/14)の表示
  * 楽曲情報の投稿機能
  * 楽曲情報に対するいいね機能
* [イベント一覧画面](https://people1-history.fly.dev/events)
  * イベント一覧検索機能（イベントの種類や、開催済みか否かでの絞り込み）
* [イベント詳細画面](https://people1-history.fly.dev/events/1)
  * セットリスト投稿画面への遷移
  * 投稿されたセットリストの各楽曲に対する情報投稿機能
  * 投稿されたセットリスト情報に対するいいね機能
* [セットリスト投稿画面](https://people1-history.fly.dev/events/2/setlist/new)
※検証が難しい可能性も考え、動画を下部に添付いたします。
  * 演奏曲目の登録
  * セットリスト（演奏曲目一覧）の登録

**【サービス名】**
大衆情報局

**【サービスURL】**
https://people1-history.fly.dev/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [ ] 管理画面作成、管理画面での楽曲・イベント情報のCRUD機能
→本リリースで導入します。
- [x] Xでのユーザー認証
- [x] 楽曲・イベント一覧画面
- [x] イベントでのセットリスト投稿機能
- [x] 楽曲・イベント等に対する情報投稿・閲覧機能
- [x] 情報に対するふぁぼ機能
- [ ] ポリシー関連画面
→本リリースで導入します。
- [x] お問い合わせ等各種画面
- [x] OGP対応

## READMEレビュー時から変更した機能
* 管理画面
見積もり面談で、本リリース時に導入することになりました。
* プライバシーポリシー・利用規約
同様に、本リリース時に導入することになりました。
* 通知機能
→特に実装タイミングを定めていなかったのですが、初期ユーザー獲得のために実装した方がいいと判断し、実装しました。

## サービスイメージがわかるようなスクリーンショット等
* セットリスト登録画面
  * 演奏曲目の登録[![Image from Gyazo](https://i.gyazo.com/77df81228dd7c097384a7ba11efe196a.gif)](https://gyazo.com/77df81228dd7c097384a7ba11efe196a)
  * 演奏曲目に不備（楽曲名空欄）があった際のフラッシュメッセージ表示[![Image from Gyazo](https://i.gyazo.com/06cac509fede5994152edf07fb688555.gif)](https://gyazo.com/06cac509fede5994152edf07fb688555)
  * 正常にセットリストが登録できた際のフラッシュメッセージ表示[![Image from Gyazo](https://i.gyazo.com/7075c75bdb2796e8afbc0f01ba501277.gif)](https://gyazo.com/7075c75bdb2796e8afbc0f01ba501277)

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
