### ISSUE TITLE
Issue提出：レビュー依頼

### ISSUE THREAD

**Issue by shimada-ryuga-56a** [shimada-ryuga-56a/people1_history#70]

**Comment by shimada-ryuga-56a** [comment]
■Webアプリの概要
PEOPLE 1というアーティストの、ライブ・楽曲の概要やエピソード、豆知識などが集約されているWebサイトです。
WikipediaのPEOPLE 1特化バージョンというイメージです。
具体的には、「『この楽曲はこのような経緯で作られた』とメンバーが言っていた」「ライブのMCでこのような話をしていた」「このライブでこの楽曲はこのようにアレンジされていた」などの情報を得ることができます。
また、これらの情報はユーザーが自由に書き込むことができるため、ライブ後すぐにどんなライブだったかを発信・共有することができます。
また、年表機能（後日実装予定）もあり、PEOPLE 1が辿ってきた歴史を知ることもできます。

■1週間辺りの開発に向けられる時間
* 1週間あたり：30~40時間
* 1週間あたり16前後のストーリーポイント消化予定

■ProjectsのURL
作成したProjects（看板・issue・ストーリーポイントが確認できるもの且つ他者でも閲覧可能状態）のURLを貼り付けてください。

■MVPリリースまで
- [ ] rails new
- [ ] デプロイ
- [ ] 管理画面作成
- [ ] （管理画面）楽曲・イベント情報のCRUD機能
- [ ] Xでのユーザー認証
- [ ] 楽曲・イベント一覧画面
- [ ] イベントでのセットリスト投稿機能
- [ ] 楽曲・イベント等に対する情報投稿・閲覧機能
- [ ] 情報に対するふぁぼ機能
- [ ] ポリシー関連・お問い合わせ等各種画面
- [ ] OGP対応

■MVP後
- [ ] （管理画面）ディスコグラフィーCRUD機能
- [ ] （管理画面）PEOPLE 1メンバーCRUD機能
- [ ] （管理画面）ヒストリーCRUD機能
- [ ] メンバー・ヒストリー情報の表示
- [ ] メンバー・ヒストリーに対する情報投稿・閲覧機能
- [ ] Googleアナリティクス
- [ ] ファビコン

■MVPレビュー依頼予定日
予定日：2024年12月01日

**Comment by ippei-shimizu** [comment]
概ね良いかと思います。LGTMです。

---

以下、MVPに含めなくても良いかもと思ったカードになります。
- https://github.com/shimada-ryuga-56a/people1_history/issues/46
- https://github.com/shimada-ryuga-56a/people1_history/issues/43
- https://github.com/shimada-ryuga-56a/people1_history/issues/44
